### ISSUE TITLE
error while create autonumber

### ISSUE THREAD

**Issue by sangkilsoft** [sangkil/sangkilbiz3#2]
•SQLSTATE[42P01]: Undefined table: 7 ERROR: relation "auto_number" does not exist LINE 1: SELECT \* FROM "auto_number" WHERE ("template_group"=$1) AND ... ^ The SQL being executed was: SELECT \* FROM "auto_number" WHERE ("template_group"='purchase') AND ("template_num"='PU14.?')

**Comment by mdmunir** [comment]
Its about database migration. Should be write on docs.

**Comment by sangkilsoft** [comment]
ok, fixed after run

```
yii migrate --migrationPath=@mdm/autonumber/migrations
```
